INSERT INTO UCTABUSERS (UCIDUSER, UCUSERNAME, UCLOGIN, UCPASSWORD, UCPASSEXPIRED, UCUSEREXPIRED, UCUSERDAYSSUN, UCEMAIL, UCPRIVILEGED, UCTYPEREC, UCPROFILE, UCKEY, UCINATIVE) VALUES (1, 'admin', 'admin', 'yo5GWOQF2sbz', '19/03/2018', -1, 30, 'darlon@softlogus.com.br', -1, 'U', 2, 'xobOIWXvPhYDUiLbpUwN', 0);
INSERT INTO UCTABUSERS (UCIDUSER, UCUSERNAME, UCLOGIN, UCPASSWORD, UCPASSEXPIRED, UCUSEREXPIRED, UCUSERDAYSSUN, UCEMAIL, UCPRIVILEGED, UCTYPEREC, UCPROFILE, UCKEY, UCINATIVE) VALUES (2, 'completo', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'P', NULL, NULL, NULL);
INSERT INTO UCTABUSERS (UCIDUSER, UCUSERNAME, UCLOGIN, UCPASSWORD, UCPASSEXPIRED, UCUSEREXPIRED, UCUSERDAYSSUN, UCEMAIL, UCPRIVILEGED, UCTYPEREC, UCPROFILE, UCKEY, UCINATIVE) VALUES (3, 'desen', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'P', NULL, NULL, NULL);
INSERT INTO UCTABUSERS (UCIDUSER, UCUSERNAME, UCLOGIN, UCPASSWORD, UCPASSEXPIRED, UCUSEREXPIRED, UCUSERDAYSSUN, UCEMAIL, UCPRIVILEGED, UCTYPEREC, UCPROFILE, UCKEY, UCINATIVE) VALUES (4, 'darlon', 'darlon', 'yo5GWOQF2sbz', '28/12/2017', -1, 0, '', -1, 'U', 3, '0Ii+/DITH5sDJ1hyczK0oA', 0);

COMMIT WORK;
