
<!--  BASE PRINCIPAL -->
ALTER TABLE C000025
    ADD CEST VARCHAR(7) CHARACTER SET ISO8859_1 DEFAULT '000000' NOT NULL COLLATE ISO8859_1
	
<!-- BANCO DE DADOS PDV -->
ALTER TABLE ESTOQUE
    ADD CEST VARCHAR(7) CHARACTER SET ISO8859_1 DEFAULT '000000' NOT NULL COLLATE ISO8859_1
	
ALTER TABLE NFCE
    ADD EX INTEGER DEFAULT 0,
    ADD HORA VARCHAR(8),
    ADD CONTINGENCIA VARCHAR(1),
    ADD ENVIADOCONTINGENCIA VARCHAR(1),
    ADD MOTIVOCONTIGENCIA VARCHAR(255),
    ADD XMLENVIO BLOB SUB_TYPE 0 SEGMENT SIZE 80,
    ADD XMLCACNELAMENTO BLOB SUB_TYPE 0 SEGMENT SIZE 80,
    ADD XML_CANCELAMENTO VARCHAR(255)	
	
/* Privileges of procedures */	
GRANT INSERT ON NFCE TO PROCEDURE NFCE_INSERT;
GRANT INSERT ON CUPOM TO PROCEDURE ST_CUPOM_INSERT;
GRANT INSERT ON CUPOM_ITEM TO PROCEDURE ST_CUPOM_ITEM_INSERT;
GRANT INSERT ON NFCE TO PROCEDURE ST_NFCE_INSERT;